# Cargo package manifest
# https://doc.rust-lang.org/cargo/reference/manifest.html

# Inherit workspace lints
lints.workspace = true

# Package configuration
# https://doc.rust-lang.org/cargo/reference/manifest.html#the-package-section
[package]
# TBD: Crate name
name = "tbd-bin"
# TBD: If this crate does not follow the version of the workspace, modify this accordingly
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "TBD: Crate description"
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["TBD: Keywords"]
# https://crates.io/category_slugs
categories = ["TBD: Categories"]

# Dependencies
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
[dependencies]

# Development dependencies
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#development-dependencies
[dev-dependencies]

# Build dependencies
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#build-dependencies
[build-dependencies]
